---
- hosts: nodes
  sudo: yes
  tasks:
    - name: update and upgrade apt
      apt:  upgrade=dist update_cache=yes

    - name: install dkms unzip and wget
      apt: name="{{item}}" state=installed
      with_items:
        - dkms
        - unzip
        - wget
        - python-pip

    - pip:
        name: pexpect

    - name: add deb to source repo
      apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contr
ib' state=present

    - name: add key for virtualbox
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: install virtualbox-5.0
      apt: name=virtualbox-5.0 state=present update_cache=yes force=yes

    - user:
        name: vagrant
        group: vboxusers
        state: present

    - name: download virtual box extension
      get_url:
        url: http://download.virtualbox.org/virtualbox/5.0.24/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        dest: /home/vagrant/Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        force: yes

    - name: to check if ext pack exists
      command: VBoxManage list extpacks
      register: temp

    - name: install the downloaded virtual box extension
      expect:
        command: VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.0.24-108355.vbox-extpack
        responses:
          (?i)Do you agree to these license terms and conditions (y/n)?: "y"
      when:
        'temp.stdout=="Extension Packs: 0"'

    - name: install apache and php
      apt: name={{item}} state=present
      with_items:
        - apache2
        - php5
        - php5-mysql
        - libapache2-mod-php5

    - name: downloading phpvirtualbox
      get_url:
        url: https://sourceforge.net/projects/phpvirtualbox/files/phpvirtualbox-5.0-5.zip
        dest: /home/vagrant/phpvirtualbox-5.0-5.zip
        force: yes

    - file: path='/var/www/html/phpvirtualbox' state=directory

    - name: unzip the phpvirtualbox files
      unarchive:
        src: /home/vagrant/phpvirtualbox-5.0-5.zip
        dest: /var/www/html
        remote_src: yes

    - file:
        path: /var/www/html/phpvirtualbox-5.0-5/
        mode: 0777

    - copy:
        src: /var/www/html/phpvirtualbox-5.0-5/config.php-example
        dest: /var/www/html/phpvirtualbox-5.0-5/config.php
        remote_src: yes

    - replace:
        path: /var/www/html/phpvirtualbox-5.0-5/config.php
        regexp: "name = 'vbox'"
        replace: "name = 'vagrant'"

    - replace:
        path: /var/www/html/phpvirtualbox-5.0-5/config.php
        regexp: "word = 'pass'"
        replace: "word = 'vagrant'"

    - name: updating the /etc/default/virtualbox file
      copy:
        content: 'VBOXWEB_USER=vagrant'
        dest: /etc/default/virtualbox
        force: no

    - name: install vagrant from deb
      apt:
       deb: https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb?_ga=2.127681869.1728430659.1504721252-1913439545.1503595309

    - service:
        name: vboxweb-service
        state: restarted

    - service:
        name: vboxdrv
        state: restarted

    - service:
        name: apache2
        state: restarted

    - name: execute vagrant init
      shell: vagrant init ubuntu/trusty32

    - name: insert a block in the inner VM's vagrant file
      blockinfile:
        path: /home/vagrant/Vagrantfile
        block: |1
             config.vm.provider "virtualbox" do |vb|
                 vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
                 vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
                 vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                 vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
             end
        insertafter: '# config.vm.synced_folder "../data", "/vagrant_data"'

    - name: execute vagrant up
      shell: vagrant up
      become_user: vagrant
      become: true

    - name: execute vagrant provision
      shell: vagrant provision
      become_user: vagrant
      become: true
